#/bin/sh

#比较两个文件是否一致
function compare_file(){
    src_file=$1
    dst_file=$2
    if [ ! -f "${dst_file}" ]
    then
        echo "difference"
        return
       fi

    diff_lines=$(diff $1 $2 | grep -v "Autogenerated by Thrift" |wc -l | awk '{print $1}')

    if (( $diff_lines>2 ))
    then
        echo "difference"
    else
        echo "equally"
        return
    fi
}

#复制源文件到指定目录
function copy_folder(){
    src_folder=$1
    dst_folder=$2

    for m in $(ls $src_folder)
    do
        file_name=$(basename $m)
        result=$(compare_file ${src_folder}/${file_name} ${dst_folder}/${dst_folder})

        if [ "$result" == "difference" ]
        then
            cp  ${src_folder}/${file_name} ${dst_folder}/${file_name}
        fi
    done
}


