package com.lyl.core.dao.mapper;

import com.lyl.core.dao.domain.Galaxy;
import com.lyl.core.dao.domain.GalaxyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface GalaxyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    long countByExample(GalaxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    int deleteByExample(GalaxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    @Delete({
        "delete from galaxy",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    @Insert({
        "insert into galaxy (id, uid, ",
        "name, age, address, ",
        "phone, ext_info, ",
        "remark, caller, ",
        "invalid)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{extInfo,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{caller,jdbcType=VARCHAR}, ",
        "#{invalid,jdbcType=INTEGER})"
    })
    int insert(Galaxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    int insertSelective(Galaxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    List<Galaxy> selectByExampleWithRowbounds(GalaxyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    List<Galaxy> selectByExample(GalaxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, uid, name, age, address, phone, ext_info, remark, caller, invalid",
        "from galaxy",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.lyl.core.dao.mapper.GalaxyMapper.BaseResultMap")
    Galaxy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Galaxy record, @Param("example") GalaxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Galaxy record, @Param("example") GalaxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Galaxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     */
    @Update({
        "update galaxy",
        "set uid = #{uid,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "ext_info = #{extInfo,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "caller = #{caller,jdbcType=VARCHAR},",
          "invalid = #{invalid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Galaxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Galaxy> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table galaxy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Galaxy> list, @Param("selective") Galaxy.Column ... selective);
}