server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    name: centaur
    url: jdbc:mysql://127.0.0.1:3306/centaur?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: centaur
    password: centaur
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
##该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lyl.core.dao.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#thrift
global:
  service:
    name: centaur-core
    port: 9999
    weight: -1

sign:
  check: true #是否验签

galaxy:
  servers:
  - host: "127.0.0.1"
    port: 9999
    timeOut: 3000